[package]
name = "cli-testing-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyjson = "2.3.0"
colored = "2.0.0"
reqwest = "0.11.11"
text_io = "0.1.10"